In [1]:
import numpy as np

#### Creating array using list

In [2]:
l1 = [[1,2,3],[4,5,6],[7,8,9]]


In [4]:
a1 = np.array(l1)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Broadcasting method

In [5]:
b = a1 + 2
b

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
b1 = a1 - 2
b1

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

Obiously two array shape are same

In [9]:
l2 = [[1,2,3],[3,3,1]]

a2 = np.array(l2)

In [10]:
s = a1 + a2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 