#### ndarray Metrix Multiplication

In [4]:
import numpy as np

In [2]:
l1 = [[1,2,3],[4,5,6],[7,8,9]]


In [5]:
a1 = np.array(l1)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
l2 = [[11,21,3],[4,15,6],[7,38,9]]
a2 = np.array(l2)
a2

array([[11, 21,  3],
       [ 4, 15,  6],
       [ 7, 38,  9]])

In [7]:
a1.dot(a2)

array([[ 40, 165,  42],
       [106, 387,  96],
       [172, 609, 150]])

In [8]:
b1 = np.arange(8)
b2 = np.arange(8,16)

In [9]:
b1 @ b2

364

#### Transpose 

In [10]:
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
a1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [12]:
print(a2.T)

[[11  4  7]
 [21 15 38]
 [ 3  6  9]]


#### **Inverse**

In [14]:
a1inv = np.linalg.inv(a1)

In [15]:
print(a1inv)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
