#### Numpy Arra Manipulation

In [4]:
import numpy as np

In [5]:

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[9,8,7],[6,5,4],[3,2,1]])

In [6]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


#### Creating copy

In [7]:
a_copy = a.copy()

a_copy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a_copy[2,1] = 10

In [10]:
print(a_copy)

[[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]


In [11]:
print(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Using View

In [13]:
a_view = a.view()

print(a_view)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
a_view[1,2] = 12

print(a_view)

[[ 1  2  3]
 [ 4  5 12]
 [ 7  8  9]]


In [15]:
print(a)

[[ 1  2  3]
 [ 4  5 12]
 [ 7  8  9]]


#### tolist() Function

In [17]:
a_list = a.tolist()

a_list

[[1, 2, 3], [4, 5, 12], [7, 8, 9]]

#### array.dump("a.pkl")

In [18]:
a.dump("a.pkl")

#### array.astype(which type you convert)

In [19]:
a_int8 = a.astype(np.int8)

In [20]:
print(a_int8)

[[ 1  2  3]
 [ 4  5 12]
 [ 7  8  9]]


### Shape Manipulation

In [21]:
c = np.array([1,2,3,4,5,6,7,8,9])
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
c_reshape = c.reshape((3,3))

In [23]:
c_reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Array.resize() function inplace  

In [25]:
c_flat = c.flatten()
c_flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
c_flat.shape

(9,)

In [27]:
c_ravel = c.ravel()
c_ravel

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
c.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
c.transpose()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Element Menipulation

In [31]:
d = np.array([[1,1,1],[2,2,3],[4,4,4]])

In [37]:
d_row = np.append(d,[[7,1,2]],axis=0)
d_row

array([[1, 1, 1],
       [2, 2, 3],
       [4, 4, 4],
       [7, 1, 2]])

In [39]:
d_column = np.append(d,np.array([8,7,6]).reshape([3,1]),axis=1)

In [40]:
d_column

array([[1, 1, 1, 8],
       [2, 2, 3, 7],
       [4, 4, 4, 6]])

#### np.insert(array, object,value, axis)

In [ ]:
d_column = np.insert(d,[2],np.array([8,7,6]).reshape([3,1]),axis=1)


In [41]:
d_column

array([[1, 1, 1, 8],
       [2, 2, 3, 7],
       [4, 4, 4, 6]])

In [42]:
d_row = np.insert(d,[1],np.array([8,7,6]).reshape([3,1]),axis=1)


In [43]:
d_row

array([[1, 8, 1, 1],
       [2, 7, 2, 3],
       [4, 6, 4, 4]])

### Delete()

In [45]:
d_deleted = np.delete(d_row,[1,2],axis=1)
d_deleted

array([[1, 1],
       [2, 3],
       [4, 4]])

#### Value Manipulation and Array Join

In [47]:
print(d)

[[1 1 1]
 [2 2 3]
 [4 4 4]]


In [48]:
d_sorted = np.sort(d,axis=0)
d_sorted

array([[1, 1, 1],
       [2, 2, 3],
       [4, 4, 4]])

In [50]:
d.sort()
d

array([[1, 1, 1],
       [2, 2, 3],
       [4, 4, 4]])

#### **Array Join**

In [51]:
print(a)

[[ 1  2  3]
 [ 4  5 12]
 [ 7  8  9]]


In [52]:
print(d)

[[1 1 1]
 [2 2 3]
 [4 4 4]]


In [53]:
print(b)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [54]:
a_and_b = np.concatenate([a,b], axis=1) 

a_and_b

array([[ 1,  2,  3,  9,  8,  7],
       [ 4,  5, 12,  6,  5,  4],
       [ 7,  8,  9,  3,  2,  1]])

In [55]:
a_and_b = np.concatenate([a,b]) 

a_and_b

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 7,  8,  9],
       [ 9,  8,  7],
       [ 6,  5,  4],
       [ 3,  2,  1]])

In [56]:
a_and_b = np.vstack([a,b]) 

a_and_b

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 7,  8,  9],
       [ 9,  8,  7],
       [ 6,  5,  4],
       [ 3,  2,  1]])