ndarray.max()
ndarray.argmax()
ndarray.min()
ndarray.armin()
ndarray.sum()
ndarray.mean()
ndarray.var()
ndarray.std()
ndarray.prod()
ndarray.round()

In [1]:
import numpy as np


In [2]:
l1 = [[1,2,3],[4,5,6],[7,8,9]]
a1 = np.array(l1)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
a1.max()

9

In [5]:
a1.max(axis=1) #each Row max

array([7, 8, 9])

In [6]:
a1.max(axis=0)#Each column max

array([7, 8, 9])

In [7]:
a1.argmax() # Which index for maxmimum value

8

In [9]:
a1.argmax(axis=1)

array([2, 2, 2])

In [10]:
a1.min()

1

In [11]:
a1.argmin()

0

In [12]:
a1.argmin(axis=1)

array([0, 0, 0])

In [13]:
a1.sum()

45

In [14]:
a1.mean()

5.0

In [15]:
a1.var()

6.666666666666667

In [16]:
a1.std()

2.581988897471611

In [17]:
a1.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [18]:
a1.prod() #Each element multiple 

362880

In [21]:
a2 = np.random.random((3,3))
a2

array([[0.99664183, 0.93579723, 0.76907108],
       [0.90083204, 0.35590123, 0.49761638],
       [0.14423305, 0.18359473, 0.65411072]])

In [22]:
a2.round(2)

array([[1.  , 0.94, 0.77],
       [0.9 , 0.36, 0.5 ],
       [0.14, 0.18, 0.65]])